version: '3'

services:
  netprotocolhub:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8082:8082"
      - "8883:8883"
    volumes:
      - ./images:/app/images
      - ./images_received:/app/images_received
    restart: always
